CREATE TABLE User (
    UserID INT(6) UNSIGNED ZEROFILL AUTO_INCREMENT PRIMARY KEY,
    Username VARCHAR(255),
    Password VARCHAR(255),
    FirstName VARCHAR(255),
    LastName VARCHAR(255),
    Email VARCHAR(255)
);

CREATE TABLE Department (
    DepartmentID INT(6) UNSIGNED ZEROFILL AUTO_INCREMENT PRIMARY KEY,
    DepartmentName VARCHAR(255)
);

CREATE TABLE Document (
    DocumentID INT(6) UNSIGNED ZEROFILL AUTO_INCREMENT PRIMARY KEY,
    Title VARCHAR(255),
    Content TEXT,
    DateCreated TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    LastModified TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UserID INT(6) UNSIGNED ZEROFILL,
    DepartmentID INT(6) UNSIGNED ZEROFILL,
    StatusID INT(6) UNSIGNED ZEROFILL,
    FOREIGN KEY (UserID) REFERENCES User(UserID),
    FOREIGN KEY (DepartmentID) REFERENCES Department(DepartmentID),
    FOREIGN KEY (StatusID) REFERENCES Status(StatusID)
);

CREATE TABLE TrackingHistory (
    TrackingID INT(6) UNSIGNED ZEROFILL AUTO_INCREMENT PRIMARY KEY,
    DocumentID INT(6) UNSIGNED ZEROFILL,
    StatusID INT(6) UNSIGNED ZEROFILL,
    UserID INT(6) UNSIGNED ZEROFILL,
    DateUpdated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (DocumentID) REFERENCES Document(DocumentID),
    FOREIGN KEY (StatusID) REFERENCES Status(StatusID),
    FOREIGN KEY (UserID) REFERENCES User(UserID)
);
